# Generated by Django 4.0 on 2023-02-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='id',
        ),
        migrations.AddField(
            model_name='choice',
            name='_id',
            field=models.AutoField(default=3, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
