# Generated by Django 4.0 on 2023-02-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_poll',
            field=models.BooleanField(default=False),
        ),
    ]
