# Generated by Django 4.0 on 2023-02-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_is_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='has_photo',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='link',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='postImage',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
