# Generated by Django 4.0 on 2023-02-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('donations', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transactions',
            new_name='Transaction',
        ),
    ]
